### PR TITLE
Fix static inner classes being intended one too many times

### PR DESCRIPTION
**Pull request by kashike**
Adds new `proper-inner-class-indenting` option

### CODE REVIEW

**Comment by AbrarSyed** [comment]
I think you should specify an explicit default value of true, and then allow it to be disabled.

**Comment by kashike** [comment]
You wanted the option so we don't break 1.8, making it default would break that, would it not?

**Comment by AbrarSyed** [comment]
not 1.8, it will break 1.8.9. This change will onyl be used for FG 2.1+. No need to split FG versions between them as there ar eno significant workflow changes unlike previous MC versions.

**Comment by kashike** [comment]
:tada: :fireworks: :dancer: :dancers:

**Comment by LexManos** [comment]
This doesn't actually fix the situation. It cleans up classes but it screws up methods.
http://puu.sh/nqJgu/14271b4327.png

**Pull request merged**
